ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

# Download dependencies for zed SDK
RUN apt-get update && apt-get install -y --no-install-recommends \
    lsb-release \
    wget \
    less \
    zstd \
    udev \
    sudo \
    apt-transport-https \
    && rm -rf /var/lib/apt/lists/*

# ZED SDK for ARM64 (Jetson)
RUN --mount=type=cache,target=/var/cache/apt \
    wget -q --no-check-certificate -O ZED_SDK_Linux.run https://download.stereolabs.com/zedsdk/4.2/l4t36.3/jetsons \
    && chmod +x ./ZED_SDK_Linux.run \
    && ./ZED_SDK_Linux.run silent skip_od_module skip_python skip_cuda \
    && rm ZED_SDK_Linux.run

RUN ln -sf /lib/aarch64-linux-gnu/libusb-1.0.so.0 /usr/lib/aarch64-linux-gnu/libusb-1.0.so